language: go

go:
  - 1.14.x

services:
  - docker

before_install:
  - docker build -t bbarrington/web-test .
  - docker run -d bbarrington/web-test /bin/sh -c "cd /go/src/github.com/bbarrington42/web-test; go test -v ./...;"
  - docker ps -a
